var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/bookings/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0o2ika5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_09vd311.js")
R.c("server/chunks/ssr/[root-of-the-server]__05d258v._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0dgx1mn._.js")
R.c("server/chunks/ssr/src_0q58iwe._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_admin_layout_tsx_09lym7.._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_bookings_page_actions_0hi9dzq.js")
R.m(23837)
module.exports=R.m(23837).exports
