var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/faqs/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xb7ye.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0du4f4e.js")
R.c("server/chunks/ssr/[root-of-the-server]__05d258v._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0dgx1mn._.js")
R.c("server/chunks/ssr/src_0q58iwe._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_admin_layout_tsx_09lym7.._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_faqs_page_actions_0yewewp.js")
R.m(74070)
module.exports=R.m(74070).exports
